baseURL = 'https://italianocongeoff.vercel.app/'
languageCode = 'en-us'
title = 'Italiano con Geoff'

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'auto'

[menu]
  [[menu.main]]
    name = "Lessons"
    url = "/docs/lessons/"
    weight = 3
  [[menu.main]]
    name = "Resources"
    url = "/docs/resources/"
    weight = 2
  [[menu.main]]
    name = "Structure"
    url = "/docs/structure/"
    weight = 1

[markup.goldmark.renderer]
  unsafe = true
